package no.nav.eessi.pensjon.services.pdf
class CountryData {

    val countries = mapOf(
        "NO" to "Norge",
        "SE" to "Sverige",
        "DK" to "Danmark",
        "AF" to "Afghanistan",
        "AX" to "Åland",
        "AL" to "Albania",
        "DZ" to "Algerie",
        "AS" to "Amerikansk Samoa",
        "AD" to "Andorra",
        "AO" to "Angola",
        "AI" to "Anguilla",
        "AQ" to "Antarctica",
        "AG" to "Antigua og Barbuda",
        "AR" to "Argentina",
        "AM" to "Armenia",
        "AW" to "Aruba",
        "AZ" to "Aserbajdsjan",
        "AU" to "Australia",
        "BS" to "Bahamas",
        "BH" to "Bahrain",
        "BD" to "Bangladesh",
        "BB" to "Barbados",
        "BE" to "Belgia",
        "BZ" to "Belize",
        "BJ" to "Benin",
        "BM" to "Bermuda",
        "BT" to "Bhutan",
        "BT" to "Bhutan",
        "BO" to "Bolivia",
        "BO" to "Bolivia",
        "BQ" to "Bonaire",
        "BA" to "Bosnia Hercegovina",
        "BW" to "Botswana",
        "BV" to "Bouvetøya",
        "BR" to "Brasil",
        "BN" to "Brunei",
        "BG" to "Bulgaria",
        "BF" to "Burkina Faso",
        "BI" to "Burundi",
        "CA" to "Canada",
        "KY" to "Caymanøyene",
        "CL" to "Chile",
        "CX" to "Christmasøya",
        "CO" to "Colombia",
        "IO" to "Det Britisk Territoriet i Indiahavet",
        "VG" to "De Britiske Jomfruøyene",
        "CD" to "Den Demokratiske Republikk Kongo",
        "DO" to "Den Dominikanske Republikk",
        "AE" to "De Forente Arabiske Emirater",
        "TF" to "Den Franske Sørterritoria",
        "VA" to "Den Hellige Stol",
        "CF" to "Den Sentralafrikanske Republikk",
        "CK" to "Cookøyene",
        "CR" to "Costa Rica",
        "CU" to "Cuba",
        "CW" to "Curaçao",
        "DJ" to "Djibouti",
        "DM" to "Dominica",
        "EC" to "Ecuador",
        "EG" to "Egypt",
        "SV" to "El Salvador",
        "CI" to "Elfenbenskysten",
        "GQ" to "Ekvatorial Guinea",
        "ER" to "Eritrea",
        "EE" to "Estland",
        "ET" to "Etiopia",
        "FK" to "Falklandøyene",
        "FO" to "Færøyene",
        "FJ" to "Fiji",
        "PH" to "Filippinene",
        "FI" to "Finland",
        "FR" to "Frankrike",
        "GF" to "Fransk Guiana",
        "PF" to "Fransk Polynesia",
        "GA" to "Gabon",
        "GM" to "Gambia",
        "GE" to "Georgia",
        "GH" to "Ghana",
        "GI" to "Gibraltar",
        "GL" to "Grønland",
        "GD" to "Grenada",
        "GP" to "Guadeloupe",
        "GU" to "Guam",
        "GT" to "Guatemala",
        "GG" to "Guernsey",
        "GW" to "Guinea-Bissau",
        "GY" to "Guyana",
        "HT" to "Haiti",
        "HM" to "Heardøya og McDonaldøyene",
        "GR" to "Hellas",
        "HN" to "Honduras",
        "HK" to "Hong Kong",
        "BY" to "Hviterussland",
        "IN" to "India",
        "ID" to "Indonesia",
        "IS" to "Island",
        "IQ" to "Irak",
        "IR" to "Iran",
        "IE" to "Irland",
        "IL" to "Israel",
        "IT" to "Italia",
        "JM" to "Jamaica",
        "JP" to "Japan",
        "YE" to "Jemen",
        "JE" to "Jersey",
        "VI" to "Jomfruøyene (U.S.)",
        "JO" to "Jordan",
        "KZ" to "Kazakhstan",
        "KH" to "Kambodsja",
        "CM" to "Kamerun",
        "CV" to "Kapp Verde",
        "KE" to "Kenya",
        "CN" to "Kina",
        "KG" to "Kirgisistan",
        "KI" to "Kiribati",
        "KM" to "Komorene",
        "CG" to "Kongo",
        "XK" to "Kosovo",
        "HR" to "Kroatia",
        "CY" to "Kypros",
        "KW" to "Kuwait",
        "LA" to "Laos",
        "LV" to "Latvia",
        "LS" to "Lesotho",
        "LS" to "Lesotho",
        "LB" to "Libanon",
        "LR" to "Liberia",
        "LY" to "Libya",
        "LI" to "Liechtenstein",
        "LT" to "Litauen",
        "LU" to "Luxembourg",
        "MO" to "Macau",
        "MK" to "Makedonien",
        "MG" to "Madagaskar",
        "MW" to "Malawi",
        "MY" to "Malaysia",
        "MV" to "Maldivene",
        "ML" to "Mali",
        "MT" to "Malta",
        "IM" to "Man",
        "MH" to "Marshalløyene",
        "MQ" to "Martinique",
        "MR" to "Mauritania",
        "MU" to "Mauritius",
        "YT" to "Mayotte",
        "MX" to "Mexico",
        "FM" to "Mikronesia",
        "MD" to "Moldova",
        "MC" to "Monaco",
        "MN" to "Mongolia",
        "ME" to "Montenegro",
        "MS" to "Montserrat",
        "MA" to "Morokko",
        "MZ" to "Mosambik",
        "MM" to "Myanmar",
        "NA" to "Namibia",
        "NR" to "Nauru",
        "NL" to "Nederland",
        "NP" to "Nepal",
        "NZ" to "New Zealand",
        "NI" to "Nicaragua",
        "NE" to "Niger",
        "NG" to "Nigeria",
        "NU" to "Niue",
        "NF" to "Norfolkøya",
        "KP" to "Nord-Korea",
        "MP" to "Nord-Marianene",
        "NC" to "Ny-Caledonia",
        "OM" to "Oman",
        "PK" to "Pakistan",
        "PW" to "Palau",
        "PS" to "Palestine",
        "PA" to "Panama",
        "PG" to "Papua Ny-Guinea",
        "PY" to "Paraguay",
        "PE" to "Peru",
        "PN" to "Pitcairnøyene",
        "PL" to "Polen",
        "PT" to "Portugal",
        "PR" to "Puerto Rico",
        "QA" to "Qatar",
        "RE" to "Réunion",
        "RO" to "Romania",
        "RU" to "Russland",
        "RW" to "Rwanda",
        "BL" to "Saint Barthélemy",
        "SH" to "Saint Helena",
        "KN" to "Saint Kitts og Nevis",
        "LC" to "Saint Lucia",
        "MF" to "Saint Martin",
        "PM" to "Saint Pierre og Miquelon",
        "VC" to "Saint Vincent og Grenadinene",
        "SB" to "Salomonøyene",
        "WS" to "Samoa",
        "SM" to "San Marino",
        "ST" to "São Tomé og Príncipe",
        "SA" to "Saudi Arabia",
        "SN" to "Senegal",
        "RS" to "Serbia",
        "SC" to "Seychellene",
        "SL" to "Sierra Leone",
        "SG" to "Singapore",
        "SX" to "Sint Maarten",
        "SK" to "Slovakia",
        "SI" to "Slovenia",
        "SO" to "Somalia",
        "ZA" to "Sør-Africa",
        "GS" to "Sør-Georgia",
        "KR" to "Sør-Korea",
        "SS" to "Sør-Sudan",
        "ES" to "Spania",
        "LK" to "Sri Lanka",
        "GB" to "Storbritannia",
        "SD" to "Sudan",
        "SR" to "Surinam",
        "SJ" to "Svalbard og Jan Mayen",
        "SZ" to "Swaziland",
        "CH" to "Sveits",
        "SY" to "Syria",
        "TW" to "Taiwan",
        "TJ" to "Tadsjikistan",
        "TZ" to "Tanzania",
        "TH" to "Thailand",
        "CZ" to "Tsjekkia",
        "TG" to "Togo",
        "TK" to "Tokelau",
        "TO" to "Tonga",
        "TT" to "Trinidad og Tobago",
        "TD" to "Tsjad",
        "TN" to "Tunisia",
        "TR" to "Tyrkia",
        "TM" to "Turkmenistan",
        "TC" to "Turks- og Caicosøyene",
        "TV" to "Tuvalu",
        "DE" to "Tyskland",
        "UG" to "Uganda",
        "UA" to "Ukraina",
        "HU" to "Ungarn",
        "US" to "USA (Amerikas Forente Stater)",
        "UY" to "Uruguay",
        "UZ" to "Usbekistan",
        "VU" to "Vanuatu",
        "VE" to "Venezuela",
        "EH" to "Vest-Sahara",
        "VN" to "Vietnam",
        "WF" to "Wallis og Futuna",
        "ZM" to "Zambia",
        "ZW" to "Zimbabwe",
        "AT" to "Østerrike",
        "TL" to "Øst Timor"
    )

    fun getLabel(key: String) : String {
        if (countries.containsKey(key.toUpperCase())) {
            return countries.get(key.toUpperCase())!!
        }
        return key
    }
}
