kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-saksbehandling-api-q2
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  gcp:
    buckets:
      - name: eessi-pensjon-saksbehandling-api-dev
        retentionPeriodDays: 30
        lifecycleCondition:
          age: 7
          createdBefore: 2020-01-01
          numNewerVersions: 2
          withState: ANY
        uniformBucketLevelAccess: true
  envFrom:
    - secret: saksbehandlingapi-dev #secret name in Google Secret Manager
  azure:
    application:
      enabled: true
      claims:
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: eessi-pensjon-frontend-ui-q2
          namespace: eessipensjon
          cluster: dev-gcp
  webproxy: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: test
    - name: ENV
      value: q2
    - name: GCP_BUCKET_NAME
      value: eessi-pensjon-saksbehandling-api-dev
    - name: PENSJON_UTLAND_WS_ALLOWED_ORIGINS_URL
      value: https://pensjon-utland-q2.dev.intern.nav.no
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: KAFKA_BROKERS_URL
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: EESSI_PEN_ONPREM_PROXY_URL
      value: https://eessi-pensjon-onprem-proxy-q2.dev-fss-pub.nais.io
    - name: KAFKA_SEDSENDT_TOPIC
      value: eessi-basis-sedSendt-v1-q2
    - name: KAFKA_SEDMOTTATT_TOPIC
      value: eessi-basis-sedMottatt-v1-q2
    - name: AZURE_APP_PROXY_CLIENT_ID
      value: dev-fss.eessipensjon.eessi-pensjon-onprem-proxy-q2

  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-frontend-api-q2.dev.intern.nav.no
    - https://eessi-pensjon-saksbehandling-api-q2.dev.intern.nav.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 40
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 40
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50