kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-saksbehandling-api-q1
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  kafka:
    pool: nav-dev
  gcp:
    buckets:
      - name: eessi-pensjon-saksbehandling-api-dev-q1
        retentionPeriodDays: 30
        lifecycleCondition:
          age: 7
          createdBefore: 2020-01-01
          numNewerVersions: 2
          withState: ANY
        uniformBucketLevelAccess: true
  envFrom:
    - secret: saksbehandlingapi-dev #secret name in Google Secret Manager
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: 6e921c7e-7b22-4c9a-9ff6-ee3719e3c4ba #Tilgang til 0000-ga-eessi-clerk-pensjon
          - id: 79c6b5b5-1144-495c-a2c9-78aebfb5faf4 #Tilgang til 0000-ga-eessi-clerk-ufore
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: eessi-pensjon-frontend-ui-q1
          namespace: eessipensjon
          cluster: dev-gcp
        - application: eessi-pensjon-frontend-ui-q1-experimental
          namespace: eessipensjon
          cluster: dev-gcp
    outbound:
      rules:
        - application: logging
          namespace: nais-system
      external:
        - host: eessi-pensjon-fagmodul-q1.intern.dev.nav.no
        - host: ldapgw.preprod.local
          ports:
            - port: 636
  webproxy: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: test
    - name: ENV
      value: q1
    - name: GCP_BUCKET_NAME
      value: eessi-pensjon-saksbehandling-api-dev-q1
    - name: PENSJON_UTLAND_WS_ALLOWED_ORIGINS_URL
      value: https://pensjon-utland-q1.intern.dev.nav.no
    - name: KAFKA_SEDSENDT_TOPIC
      value: eessibasis.sedsendt-v1-q1
    - name: KAFKA_SEDMOTTATT_TOPIC
      value: eessibasis.sedmottatt-v1-q1
    - name: LDAP_USER_BASEDN
      value: ou=NAV,ou=BusinessUnits,dc=preprod,dc=local
    - name: LDAP_SERVICEUSER_BASEDN
      value: ou=ServiceAccounts,dc=preprod,dc=local
    - name: LDAP_DOMAIN
      value: PREPROD.LOCAL
    - name: LDAP_BASEDN
      value: dc=preprod,dc=local
    - name: LDAP_URL
      value: ldaps://ldapgw.preprod.local:636

  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-frontend-api-q1.intern.dev.nav.no
    - https://eessi-pensjon-saksbehandling-api-q1.intern.dev.nav.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 40
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 40
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 380Mi
