kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-saksbehandling-api
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  kafka:
    pool: nav-prod
  gcp:
    buckets:
      - name: eessi-pensjon-saksbehandling-api-prod
        retentionPeriodDays: 30
        lifecycleCondition:
          age: 7
          createdBefore: 2020-01-01
          numNewerVersions: 2
          withState: ANY
        uniformBucketLevelAccess: true
  envFrom:
    - secret: saksbehandlingapi #secret name in Google Secret Manager
  azure:
    application:
      enabled: true
      claims:
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: eessi-pensjon-frontend-ui
          namespace: eessipensjon
          cluster: prod-gcp
  webproxy: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: ENV
      value: p
    - name: GCP_BUCKET_NAME
      value: eessi-pensjon-saksbehandling-api-prod
    - name: PENSJON_UTLAND_WS_ALLOWED_ORIGINS_URL
      value: https://pensjon-utland.intern.nav.no
    - name: EESSI_PEN_ONPREM_PROXY_URL
      value: https://eessi-pensjon-onprem-proxy.prod-fss-pub.nais.io
    - name: KAFKA_SEDSENDT_TOPIC
      value: eessibasis.sedsendt-v1
    - name: KAFKA_SEDMOTTATT_TOPIC
      value: eessibasis.sedmottatt-v1
    - name: AZURE_APP_PROXY_CLIENT_ID
      value: prod-fss.eessipensjon.eessi-pensjon-onprem-proxy

  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-frontend-api.intern.nav.no
    - https://eessi-pensjon-saksbehandling-api.intern.nav.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 40
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 40
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 4000m
      memory: 1Gi
    requests:
      cpu: 2000m
      memory: 1Gi
