kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-saksbehandling-api
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  gcp:
    buckets:
      - name: eessi-pensjon-saksbehandling-api-prod
        retentionPeriodDays: 30
        lifecycleCondition:
          age: 7
          createdBefore: 2020-01-01
          numNewerVersions: 2
          withState: ANY
        uniformBucketLevelAccess: true
  envFrom:
    - secret: saksbehandlingapi #secret name in Google Secret Manager
  azure:
    application:
      enabled: true
      claims:
        extra:
          - NAVident
#  accessPolicy:
#    inbound:
#      rules:
#        - application: eessi-pensjon-frontend-ui-fss
#          namespace: eessipensjon
#          cluster: prod-gcp
  webproxy: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: ENV
      value: p
    - name: GCP_BUCKET_NAME
      value: eessi-pensjon-saksbehandling-api-prod
    - name: PENSJON_UTLAND_WS_ALLOWED_ORIGINS_URL
      value: https://pensjon-utland.nais.adeo.no
    - name: PDL_URL
      value: https://pdl-api.nais.adeo.no/graphql
    - name: KAFKA_BROKERS_URL
      value: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SASL_SSL://a01apvl00145.adeo.no:8443,SASL_SSL://a01apvl00146.adeo.no:8443,SASL_SSL://a01apvl00147.adeo.no:8443,SASL_SSL://a01apvl00149.adeo.no:8443
    - name: EESSI_PEN_ONPREM_PROXY_URL
      value: https://eessi-pensjon-onprem-proxy.prod-fss-pub.nais.io
    - name: KAFKA_SEDSENDT_TOPIC
      value: eessi-basis-sedSendt-v1
    - name: KAFKA_SEDMOTTATT_TOPIC
      value: eessi-basis-sedMottatt-v1
    - name: AZURE_APP_PROXY_CLIENT_ID
      value: prod-fss.eessipensjon.eessi-pensjon-onprem-proxy

  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-frontend-api-fss.intern.nav.no
    - https://eessi-pensjon-saksbehandling-api.intern.nav.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 40
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 40
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "4"
      memory: 4096Mi
    requests:
      cpu: 400m
      memory: 1024Mi