kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-saksbehandling-api
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  gcp:
    buckets:
      - name: eessi-pensjon-saksbehandling-api-prod
        uniformBucketLevelAccess: true
  envFrom:
    - secret: saksbehandlingapi #secret name in Google Secret Manager
    - secret: eessi-pensjon-saksbehandling-api-unleash-api-token
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: 49d708e9-c141-4a01-9be9-aa539c48f1d2 #Tilgang til 0000-ga-eessi-clerk-pensjon
          - id: fedabd32-4cab-4307-ad69-ea24edc69790 #Tilgang til 0000-ga-eessi-clerk-ufore
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: eessi-pensjon-frontend-ui
          namespace: eessipensjon
          cluster: prod-gcp
    outbound:
      external:
        - host: eessi-pensjon-fagmodul.intern.nav.no
        - host: eessipensjon-unleash-api.nav.cloud.nais.io
        - host: ldapgw.adeo.no
        - host: ldapgw.adeo.no
          ports:
            - port: 636

  webproxy: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: ENV
      value: p

    #UNLEASH
    - name: UNLEASH_ENDPOINT_URL
      value: https://unleash.nais.io/api/

    - name: UNLEASH_APP_NAME
      value: eessi-pensjon-saksbehandling-api

    - name: UNLEASH_URL
      value:  "https://eessipensjon-unleash-api.nav.cloud.nais.io/api"

    - name: GCP_BUCKET_NAME
      value: eessi-pensjon-saksbehandling-api-prod

    - name: PENSJON_UTLAND_WS_ALLOWED_ORIGINS_URL
      value: https://pensjon-utland.intern.nav.no

    - name: KAFKA_SEDSENDT_TOPIC
      value: eessibasis.sedsendt-v1
    - name: KAFKA_SEDMOTTATT_TOPIC
      value: eessibasis.sedmottatt-v1

    - name: LDAP_DOMAIN
      value: ADEO.NO
    - name: LDAP_BASEDN
      value: dc=adeo,dc=no
    - name: LDAP_URL
      value: ldaps://ldapgw.adeo.no
    - name: LDAP_USER_BASEDN
      value: ou=NAV,ou=BusinessUnits,dc=adeo,dc=no
    - name: LDAP_SERVICEUSER_BASEDN
      value: ou=ServiceAccounts,dc=adeo,dc=no

  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-frontend-api.intern.nav.no
    - https://eessi-pensjon-saksbehandling-api.intern.nav.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 40
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 40
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 2000m
      memory: 1Gi
    requests:
      cpu: 256m
      memory: 800Mi
