apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: eessi-pensjon-saksbehandling-api-q2
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: eessipensjon
  secretName: eessi-pensjon-saksbehandling-api-q2-unleash-api-token

  # Specify which environment the API token should be created for.
  # Can be one of: development, or production.
  environment: development