name: Build, push, and deploy

on:
  push:
    branches:
      - master
jobs:
  tag_build_and_deploy:
    name: 'Build, deploy and tag'
    runs-on: ubuntu-latest
    steps:
      # PULLER REPO
      - name: 'Pull repo'
        uses: actions/checkout@v1

      # SETTER DATO OG COMMIT VARIABEL
      - name: 'Setter dato og commit variabel'
        run: |
          export TZ=CET
          echo "::set-env name=DATE::$(date "+%Y-%m-%d--%H-%M-%S")"
          echo "::set-env name=COMMIT_HASH::$(git rev-parse HEAD)"

      # SETTER IMAGE VARIABEL
      - name: 'Setter Image'
        run: echo "::set-env name=IMAGE::docker.pkg.github.com/${{ github.repository }}/eessi-pensjon-saksbehandling-api:${{ env.DATE }}---${{ env.COMMIT_HASH }}"

      # BYGGER DOCKER CONTAINER
      - name: 'Bygg og publiser docker image'

        run: |
          ./gradlew -Pgithub clean build
          docker build --tag ${{ env.IMAGE }} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${{ secrets.GITHUB_TOKEN }}
          docker push ${{ env.IMAGE }}
      # OPPRETTER GIT TAG
      - name: 'Opprett git tag'
        run: |
          curl -v -s -X POST https://api.github.com/repos/navikt/eessi-pensjon-saksbehandling-api/git/refs -H "Authorization: token  ${{ secrets.GITHUB_TOKEN }}" -d '{ "ref": "refs/tags/${{ env.DATE }}---${{ env.COMMIT_HASH }}",  "sha": "${{ env.COMMIT_HASH }}" }'