name: Bygg og deploy Q2

on:
  push:
    branches:
      - master
jobs:
  tag_build_and_deploy:
    name: 'Build, deploy and tag'
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v1

      - name: 'Set date and commit hash'
        run: |
          export TZ=CET
          echo "DATE=$(date "+%Y-%m-%d--%H-%M-%S")" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: 'Set image-tag'
        run: echo "IMAGE=ghcr.io/${{ github.repository }}/eessi-pensjon-saksbehandling-api:${{ env.DATE }}---${{ env.COMMIT_HASH }}" >> $GITHUB_ENV

      - name: 'Java 17'
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 17

      - name: 'Build and publish docker image'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew build
          docker build --tag ${{ env.IMAGE }} .
          docker login ghcr.io -u ${GITHUB_REPOSITORY} -p ${{ secrets.GITHUB_TOKEN }}
          docker push ${{ env.IMAGE }}

      - name: 'Deploy to Q2 GCP'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/dev-gcp.yml
          IMAGE: ${{ env.IMAGE }}

      - name: 'Create git-tag'
        run: |
          curl -v -s -X POST https://api.github.com/repos/navikt/eessi-pensjon-saksbehandling-api/git/refs -H "Authorization: token  ${{ secrets.GITHUB_TOKEN }}" -d '{ "ref": "refs/tags/${{ env.DATE }}---${{ env.COMMIT_HASH }}",  "sha": "${{ env.COMMIT_HASH }}" }'

      - name: 'Dispatch deploy to PROD GCP'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: ${{ github.repository }}
          event-type: deploy-prod-gcp
          client-payload: '{"image": "${{ env.IMAGE }}"}'
