name: Deploy PROD
on:
  repository_dispatch:
    types: [deploy-prod]
jobs:
  tag_deploy_q1:
    name: 'Deploy til PROD'
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v2

      - name: 'Show image-tag'
        run: |
          echo "image-tag: ${{ github.event.client_payload.image }}"

      - name: 'Deploy to PROD'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: nais/prod-fss.yml
          VARS: nais/prod-fss.json
          IMAGE: ${{ github.event.client_payload.image }}